stages:
  - build
  - it

build-job:
  stage: build
  image: openjdk:17.0.2
  script:
    - echo 'Ez a build lépés'
    - ./mvnw package
  artifacts:
    paths:
      - target/*.jar

it-job:
  stage: it
  script:
    - echo 'Ez az integrációs teszek lépés'