FROM openjdk:17.0.2 as builder
WORKDIR app
COPY pom.xml .
COPY .mvn/ .mvn/
COPY mvnw .
COPY src src/
RUN ./mvnw -B package

FROM openjdk:17.0.2
WORKDIR app
COPY --from=builder /app/target/*.jar ./employees.jar
ENTRYPOINT [ "java", "-jar", "employees.jar" ]